export enum FunctionEnum{
    main = 1,
    manageMedium = 2,
    manageStorage = 3,
    ovumBankTransfer=4,
    treatmentSummary=5,
    freezingSummary=6,
    ovumPickupNote=7,
    thawOvum=8,
    thawEmbryo=9,
    observationNote=10,
    operateSperm=11,
    transferInFromOther=12,
    uploadReport=13,
    transferOut=14,
    freeze=15,
    fertilize=16,
    implant=17,
    incubationSuspend=18,
    report=19,
    treatmentSuspend=20,
    freezeSperm = 22,
    spermScore1 = 23,
    spermScore2 = 24,
    thawSperm = 25,
    spermScore3 = 26,
    spermScore4 = 27,

    subThawOvum = 31
}