export enum FunctionEnum{
    main = 1,
    manageMedium = 2,
    manageStorage = 3,
    ovumBankTransfer=4,
    treatmentSummary=5,
    freezingSummary=6,
    ovumPickupNote=7,
    thawOvum=8,
    thawEmbryo=9,
    observationNote=10,
    operateSperm=11,
    transferInFromOther=12,
    uploadReport=13,
    transferOut=14,
    freeze=15,
    fertilize=16,
    implant=17,
    incubationSuspend=18,
    report=19,
    treatmentSuspend=20
}